### ISSUE TITLE
XEP-0357 compatibility

### ISSUE THREAD

**Issue by royneary** [ChatSecure/ChatSecure-Push-Server#4] opened 2015-03-18 20:10 UTC
Hi Chris,

based on a quick look at version 3.1 of your specification I think it can be compatible with brand new XEP-0357.

I think the 'white_list_token' in your spec is equivalent to the 'secret' and the 'api_endpoint' can be mapped to the name of a node allocated on the app server's pubusb service.

I'm not sure about the app_bundle_id and what the XMPP server should do with it.

So when Alice registers at the ChatSecure push server, it allocates a 'publish-only' node on its pubsub service and sends the node name and a white_list_token back to Alice.
Let's assume Alice has received node name "ABC" and white_list_token "DEF". Then she would enable push at her XMPP server like this:

```xml
<iq from='alice@wonderland.org/rabbithole' type='set' id='x43'>
  <enable xmlns='urn:xmpp:push:0' jid='pubsub.chatsecure.org' node='ABC'>
    <x xmlns='jabber:x:data'>
      <field var='FORM_TYPE'><value>http://jabber.org/protocol/pubsub#publish-options</value></field>
      <field var='secret'><value>DEF<value></field>
    </x>
  </enable>
</iq>
```
If Alice's XMPP server wants to send her a push notification it publishes a notification on ChatSecure's pubsub service:

```xml
<iq type='set'
    from='alice@wonderland.org'
    to='pubsub.chatsecure.org'
    id='n12'>
  <pubsub xmlns='http://jabber.org/protocol/pubsub'>
    <publish node='ABC'>
      <item>
        <notification xmlns='urn:xmpp:push:0'>
          <x xmlns='jabber:x:data'>
            <field var='FORM_TYPE'><value>urn:xmpp:push:summary</value></field>
            <field var='message-count'><value>1</value></field>
          </x>
        </notification>
      </item>
    </publish>
    <publish-options>
      <x xmlns='jabber:x:data'>
        <field var='FORM_TYPE'><value>http://jabber.org/protocol/pubsub#publish-options</value></field>
        <field var='secret'><value>DEF<value></field>
      </x>
    </publish-options>
  </pubsub>
</iq>
```
This means (as you already stated) an XMPP server with pubsub needs to be running on the ChatSecure push server.
One problem currently is that XMPP servers don't implement publish-options [1], but maybe I can fix that for ejabberd.

Christian

[1] http://www.xmpp.org/extensions/xep-0060.html#publisher-publish-options

**Comment by chrisballinger** [comment] 2015-07-14 22:19
@royneary I'm wondering if we can implement the bare minimum pubsub functionality in a standalone component without a dependency on a full XMPP server. 

Discussion on minimum viable pubsub node: https://github.com/ChatSecure/ChatSecure-Push-Server/issues/6

**Comment by chrisballinger** [comment] 2016-05-20 00:21
@royneary Hooray! We've finally sent our first XEP-0357 push using a [PubSub bridge](https://github.com/chatsecure/rubdub) that translates XMPP stanzas to push API requests. Tested with Prosody and mod_cloud_notify.

**Comment by iNPUTmice** [comment] 2016-05-20 10:03
@chrisballinger is the client side code (the one that registers with the users XMPP server) also ready? Because this would eventually fix https://github.com/ChatSecure/ChatSecure-iOS/issues/367

**Comment by chrisballinger** [comment] 2016-05-20 19:02
@iNPUTmice Yep! https://github.com/ChatSecure/ChatSecure-iOS/pull/496

Still some cleanup to do but it works. :)

**Comment by masvil** [comment] 2016-05-21 05:48
A new era is starting for ChatSecure on iOS.

**Comment by akohlsmith** [comment] 2016-05-21 15:14
@chrisballinger is there any magic needed on Prosody's side to implement this? I'd love to help beat on it.

**Comment by iNPUTmice** [comment] 2016-05-21 16:37
@akohlsmith Prosody has a basic implementation of push called mod_cloud_notify but it can and should probably be extended to follow [these business rules](http://mail.jabber.org/pipermail/standards/2016-February/030925.html).

**Comment by masvil** [comment] 2016-05-23 10:17
What are public servers supporting XEP-0357?
Do any of actually "trusted" (dukgo, jabber.calyxinstitute.org, jabber.otr.im)?
There is a great lack of information in their documentation.

**Comment by iNPUTmice** [comment] 2016-05-23 10:33
@masvil to my knowledge there are currently very few public servers that support push. 
There are:
* [trashserver.net](https://trashserver.net/xmpp/)
* [Hot-Chilli](https://jabber.hot-chilli.net/)

and we are currently working hard to implement it on [conversations.im](https://conversations.im).  But you can probably expect this to increase in the next couple of month.

**Comment by chrisballinger** [comment] 2016-05-23 18:26
I think there are some tweaks needed to `mod_cloud_notify` after some initial testing on our end. For instance it will forward extraneous things to our PubSub node like typing notifications. It also doesn't persist your push pubsub node/options configuration across server reboots. We will look into submitting PRs where necessary.

The DuckDuckGo team is pretty responsive and added a .onion endpoint not long after I reached out to their team. Once things are stabilized a bit I will reach out to their team and see if they will consider adding support.

**Comment by joecool1029** [comment] 2016-08-02 18:09
Also does not appear to be working on jabber.fr which advertises XEP-0357 support.

Compliance list of other public servers: https://gultsch.de/compliance_ranked.html

**Comment by chrisballinger** [comment] 2016-08-02 18:11
@joecool1029 We have tested with mod_cloud_notify and know that it works with our configuration. Do you know the server and 357 plugin jabber.fr are using?

**Comment by iNPUTmice** [comment] 2016-08-02 18:16
jabber.fr [uses Prosody](https://github.com/iNPUTmice/ComplianceTester/blob/master/reports/jabber.fr.txt#L39) as well.

It should be noted that ChatSecure currently still logs out completely (instead of killing the socket) and thus mod_clould_notify only triggers on offline messages. So it won't work if you are logged in with another client.

Just quickly saying this here to rule out a potential source of error.

**Comment by chrisballinger** [comment] 2016-08-02 18:26
@iNPUTmice I didn't realize that pushes wouldn't be triggered when other resources were online, but that it will push to hibernated smacks resources while others are online. I'll take another look at closing just the socket instead of doing a full teardown.

Another thing to note is that servers really should use `mod_smacks_offline` as well to prevent losing queued messages after hibernation is over.

**Comment by iNPUTmice** [comment] 2016-08-02 18:30
@chrisballinger the other benefit of hibernating smacks sessions instead of logging out is that muc messages will still reach you.

>  I didn't realize that pushes wouldn't be triggered when other resources were online,

that is a prosody limitation though fwiw. The upcoming ejabberd push module won't have this problem.

But it's still wise to do #540 if only to save traffic on a reconnect.

**Comment by joecool1029** [comment] 2016-08-02 18:42
I see that was the issue. I had a second resource online. Push is working on jabber.fr.

The only quirk I do see is that it shows me as offline until the push message wakes up the phone to reconnect. Is this intended behavior?

**Comment by iNPUTmice** [comment] 2016-08-02 18:45
> The only quirk I do see is that it shows me as offline until the push message wakes up the phone to reconnect. Is this intended behavior?

Yes and no. That is a side effect of

> It should be noted that ChatSecure currently still logs out completely (instead of killing the socket)

And @chrisballinger is going to address this in https://github.com/ChatSecure/ChatSecure-iOS/issues/540

**Comment by iNPUTmice** [comment] 2016-08-10 10:38
>> I didn't realize that pushes wouldn't be triggered when other resources were online,

> that is a prosody limitation though fwiw. The upcoming ejabberd push module won't have this problem.

[conversations.im](https://account.conversations.im) has just enabled a push module that works even if you are logged in with multiple devices.

**Closed** 2016-10-26 22:56 UTC
